import {
  ArrowRight,
  Check,
  LineChart,
  CircleDashed,
  Droplet,
  User,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Loader2,
  LogIn,
  UserPlus,
  Shield,
  Camera,
  Upload,
  LogOut,
  Menu,
  Home,
  Users,
  BarChart3,
  Settings,
  FileText,
  Search,
  Trash2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  HeartPulse,
  Heart,
  Database,
  AlertCircle,
  AlertTriangle,
  Info,
  X,
  Plus,
  Edit,
  Calendar,
  Clock,
  Crown,
  DollarSign,
  ShoppingCart,
  TrendingUp,
  Coins,
} from "lucide-react";

export const Icons = {
  cow: CircleDashed,
  milk: Droplet,
  arrowRight: ArrowRight,
  check: Check,
  analytics: LineChart,
  user: User,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  spinner: Loader2,
  loader: Loader2,
  logIn: LogIn,
  logOut: LogOut,
  userPlus: UserPlus,
  shield: Shield,
  camera: Camera,
  upload: Upload,
  menu: Menu,
  home: Home,
  users: Users,
  barChart: BarChart3,
  settings: Settings,
  fileText: FileText,
  search: Search,
  trash: Trash2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  calendar: Calendar,
  clock: Clock,
  crown: Crown,
  heartPulse: HeartPulse,
  heart: Heart,
  database: Database,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  x: X,
  plus: Plus,
  edit: Edit,
  dollarSign: DollarSign,
  shoppingCart: ShoppingCart,
  trendingUp: TrendingUp,
  coins: Coins,
};
